### ISSUE TITLE
png view error 

### ISSUE THREAD

**Issue by ghost** [ChenThread/octagon#2]
ok so ive got crc32 inflate png and pngview but when i run pngview i get

`/lib/process.lua:52: /home/pngview.lua:52: ')' expected near '&':`

and im using a tier 3 pc with tier 3 cpu, internet card, data card tier 2, graphics card tier 3, two tier 3.5 ram and a raid

**Comment by asiekierka** [comment]
Try switching to Lua 5.3 (shift-click your CPU in hand)

**Comment by ghost** [comment]
ok it works now but now i get too long without yielding

**Comment by asiekierka** [comment]
Sorry for not responding earlier - the PNG was probably too big.

The account is gone, so closing.
